default_language_version:
  # force all unspecified python hooks to run python3
  python: python3

exclude: src/main/webapp/definitions/gs-classification-api\.yaml

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-xml
      - id: check-merge-conflict
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/python-openapi/openapi-spec-validator
    rev: 0.7.2
    hooks:
      - id: openapi-spec-validator
        files: .*alfresco-.*\.(yaml|yml)
