import:
  - source: Alfresco/alfresco-build-tools:.travis.pre-commit.yml@v1.0.0

language: java
jdk: openjdk11
dist: focal

git:
  depth: false
  quiet: true

cache:
  directories:
    - ${HOME}/.m2/repository

before_cache: rm -rf $HOME/.m2/repository/org/alfresco/api-explorer

before_install:
  - cp -f .travis.settings.xml "${HOME}/.m2/settings.xml"
  - travis_retry mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

branches:
  only:
    - master
    - /feature\/.*/
    - /fix\/.*/

stages:
  - name: Lint
  - name: Test
    if: commit_message !~ /\[skip tests\]/
  - name: Release
#    if: commit_message ~= /\[release\]/ AND branch = master AND type != push AND type != pull_request AND fork = false
    if: commit_message ~= /\[release\]/ AND branch = "feature/ACS-1139_migrate-to-Travis" AND type != push AND type != pull_request AND fork = false

jobs:
  include:

    - name: "Integration Tests"
      stage: Test
      script:
        - bash CI/test.sh

    - name: "Release on NEXUS"
      stage: Release
      script:
        - bash CI/release_to_nexus.sh $RELEASE_VERSION $GITHUB_EMAIL $GITHUB_PASSWORD

#    - name: "Release on GitHub"
#      stage: Release
#      script:
#        - bash CI/release_to_github.sh $RELEASE_VERSION $GITHUB_EMAIL $GITHUB_PASSWORD $GITHUB_TOKEN
