import:
  - source: Alfresco/alfresco-build-tools:.travis.pre-commit.yml@v1.0.1
  - source: Alfresco/alfresco-build-tools:.travis.java.yml@v1.0.1

dist: focal

git:
  depth: false
  quiet: true

branches:
  only:
    - master
    - /release\/.*/
    - /feature\/.*/
    - /fix\/.*/

env:
  global:
    # Release version has to start with real version (7.1.0-....) for the docker image to build successfully.
    - RELEASE_VERSION=7.1.1-A1
    - DEVELOPMENT_VERSION=7.1.1-SNAPSHOT

stages:
  - name: lint
  - name: test
    if: commit_message !~ /\[skip tests\]/
  - name: release
    if: commit_message ~= /\[release\]/ AND (branch = master OR branch ~= /^release/) AND type != pull_request AND fork = false

jobs:
  include:

    - name: "integration tests"
      stage: test
      script:
        - bash CI/test.sh

    - name: "release on Nexus and GitHub"
      stage: release
      script:
        - bash CI/release.sh
