name: Alfresco REST API Explorer CI

on:
  pull_request:
    branches:
      - master
      - fix/**
      - feature/**
  push:
    branches:
      - master
      - fix/**
      - feature/**
  workflow_dispatch:

env:
  MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  GIT_USERNAME: ${{ secrets.BOT_GITHUB_USERNAME }}
  GIT_PASSWORD: ${{ secrets.BOT_GITHUB_TOKEN }}
  RELEASE_VERSION: "7.3.0"
  DEVELOPMENT_VERSION: "7.4.0-A1-SNAPSHOT"
  MAVEN_CLI_OPTS: "$MAVEN_CLI_OPTS -B -q -e -fae -V -DinstallAtEnd=true -U"
  GITHUB_ACTIONS_DEPLOY_TIMEOUT: 30

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v1.34.2

  build:
    name: "Build + deploy"
    runs-on: ubuntu-latest
    needs: [pre_commit]
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v1.34.2
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.34.2
      - name: "Build"
        timeout-minutes: ${{ fromJSON(env.GITHUB_ACTIONS_DEPLOY_TIMEOUT) }}
        run: mvn $MAVEN_CLI_OPTS verify -Dlogging.root.level=off -Dspring.main.banner-mode=off

  tests:
    name: "Integration tests"
    runs-on: ubuntu-latest
    needs: [build]
    if: "!contains(github.event.head_commit.message, '[skip tests]')"
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v1.34.2
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.34.2
      - name: "Run tests"
        run: bash CI/test.sh

  publish:
    name: "Publish artifacts"
    runs-on: ubuntu-latest
    needs: [tests]
    if: !failure()
    timeout-minutes: ${{ fromJSON(env.GITHUB_ACTIONS_DEPLOY_TIMEOUT) }}
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v1.34.2
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.34.2
      - name: "Publish"
        timeout-minutes: ${{ fromJSON(env.GITHUB_ACTIONS_DEPLOY_TIMEOUT) }}
        run: mvn $MAVEN_CLI_OPTS deploy -DskipTests

  release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: [publish]
    if: >
      !failure() && contains(github.event.head_commit.message, '[release]') &&
      github.ref_name == 'master' && github.event_name != 'pull_request'
    timeout-minutes: ${{ fromJSON(env.GITHUB_ACTIONS_DEPLOY_TIMEOUT) }}
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v1.34.2
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.34.2
      - name: "Release"
        run: bash CI/release.sh