name: Publish to GitHub Pages

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - master
    paths:
      - '.github/gh-pages/**'
      - 'src/main/webapp/definitions/**'

env:
  SWAGGER_UI_VERSION: 4.19.1

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build
        working-directory: .github/gh-pages
        run: ./build.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: .github/gh-pages/build

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    # Only deploy tags that are not pre-release
    if: github.event_name == 'push' && ! contains(github.ref_name, '-')
    concurrency:
      group: pages
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
