name: Publish to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SWAGGER_UI_VERSION: 4.19.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Build
        working-directory: .github/gh-pages
        run: ./build.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: .github/gh-pages/build/dist


  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'
    concurrency:
      group: pages
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
